### ISSUE TITLE
Should object pool base class be Abstract?

### ISSUE THREAD

**Issue by lucianodonati** [samizzo/TypeSafeObjectPool#1]
Question: 
Shouldn't `public class ObjectPool<T>` be an abstract class? Why/Why not?

**Thank you for your time.**

**Comment by samizzo** [comment]
Hey, thanks for your question!

I think that could go either way; it's not absolutely necessary for `ObjectPool` to be abstract. It's true that `abstract` indicates that a class is intended to be a base class of other classes, but this is also true of a generic class. A generic class *must* be a base class of some other class. Just like an abstract class, you can't instantiate a generic class (without giving it a type).

If you look at the source for [`List<T>`](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,cf7f4095e4de7646) in the .NET Framework you'll see that it's not abstract. I like to use the .NET Framework as a guideline so that's another reason to not make it abstract.

**Comment by lucianodonati** [comment]
That makes perfect sense! I overlooked the fact that it was generic and jumped into wondering why wasn't it an abstract class. But you can't instantiate T by itself, you'd need to specify it's type achieving in the process exactly what I wanted. Thanks for the answer, we are now officially two happy nerds. Cheers!
